import type { DashboardData } from './types'

export const mockDashboardData: DashboardData = {
  debtor: {
    id: 'debtor-001',
    fullName: 'Łukasz Izdebski',
  },
  loan: {
    id: 'loan-2024-001',
    principal: { amount: 23502.22, currency: 'PLN' },
    paid: { amount: 5107, currency: 'PLN' },
    remaining: { amount: 18395.22, currency: 'PLN' },
    nextPaymentDate: '2026-05-19',
  },
  installments: [
    {
      id: 'inst-1',
      number: 1,
      dueDate: '2025-09-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'paid',
    },
    {
      id: 'inst-2',
      number: 2,
      dueDate: '2025-10-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'paid',
    },
    {
      id: 'inst-3',
      number: 3,
      dueDate: '2026-11-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'paid',
    },
    {
      id: 'inst-4',
      number: 4,
      dueDate: '2025-12-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'paid',
    },
    {
      id: 'inst-5',
      number: 5,
      dueDate: '2026-01-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'paid',
    },
    {
      id: 'inst-6',
      number: 6,
      dueDate: '2026-02-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'overdue',
    },
    {
      id: 'inst-7',
      number: 7,
      dueDate: '2026-03-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'overdue',
    },
    {
      id: 'inst-8',
      number: 8,
      dueDate: '2026-04-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'overdue',
    },
    {
      id: 'inst-9',
      number: 9,
      dueDate: '2026-05-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'overdue',
    },
    {
      id: 'inst-10',
      number: 10,
      dueDate: '2026-06-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },
    {
      id: 'inst-11',
      number: 11,
      dueDate: '2026-07-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },
    {
      id: 'inst-12',
      number: 12,
      dueDate: '2026-08-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },
    {
      id: 'inst-13',
      number: 12,
      dueDate: '2026-09-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },
    {
      id: 'inst-14',
      number: 13,
      dueDate: '2026-10-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-15',
      number: 14,
      dueDate: '2026-11-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-16',
      number: 15,
      dueDate: '2026-12-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-17',
      number: 16,
      dueDate: '2027-01-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-18',
      number: 16,
      dueDate: '2027-02-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-19',
      number: 16,
      dueDate: '2027-03-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-20',
      number: 19,
      dueDate: '2027-04-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-21',
      number: 20,
      dueDate: '2027-05-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-22',
      number: 21,
      dueDate: '2027-06-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-23',
      number: 22,
      dueDate: '2027-07-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },{
      id: 'inst-24',
      number: 23,
      dueDate: '2027-08-15',
      amount: { amount: 967, currency: 'PLN' },
      status: 'pending',
    },
  ],
  payments: [
    {
      id: 'pay-1',
      date: '2025-09-23',
      amount: { amount: 967, currency: 'PLN' },
      method: 'transfer',
      reference: 'inst-1',
    },
    {
      id: 'pay-2',
      date: '2025-10-14',
      amount: { amount: 967, currency: 'PLN' },
      method: 'transfer',
      reference: 'inst-2',
    },
    {
      id: 'pay-3',
      date: '2025-10-20',
      amount: { amount: 967, currency: 'PLN' },
      method: 'transfer',
      reference: 'inst-3',
    },
    {
      id: 'pay-4',
      date: '2025-12-09',
      amount: { amount: 967, currency: 'PLN' },
      method: 'transfer',
      reference: 'inst-4',
    },
    {
      id: 'pay-5',
      date: '2025-12-09',
      amount: { amount: 272, currency: 'PLN' },
      method: 'transfer',
      reference: 'EXTRA',
    },
    {
      id: 'pay-6',
      date: '2026-04-26',
      amount: { amount: 967, currency: 'PLN' },
      method: 'transfer',
      reference: 'inst-5',
    }
  ],
}
